version: '3.1'
services:
  app:
    container_name: springboot-vault
    image: springboot-vault
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
  postgresql:
    image: postgres
    container_name: postgresql-vault
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=vaultpoc
      - POSTGRES_HOST_AUTH_METHOD=trust
